
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.chtml.script;

/** CUP generated class containing symbol constants. */
public class ScriptSym {
  /* terminals */
  public static final int GREATERTHAN = 22;
  public static final int IDPARAMETER = 56;
  public static final int MULT = 28;
  public static final int CHAR = 41;
  public static final int EQUALIZATION = 19;
  public static final int ALERT_INFO = 36;
  public static final int DESC = 30;
  public static final int SYMCHAR = 54;
  public static final int INTEGER = 38;
  public static final int RESTA = 26;
  public static final int GREATER = 24;
  public static final int REPEAT = 7;
  public static final int CARACTER_ALEATORIO = 34;
  public static final int INIT = 2;
  public static final int LESS = 23;
  public static final int REVERSE = 33;
  public static final int SEMICOLON = 45;
  public static final int NOT = 18;
  public static final int AND = 17;
  public static final int LESSTHAN = 21;
  public static final int OR = 16;
  public static final int LETIMPAR_NUM = 32;
  public static final int DIV = 27;
  public static final int OPEN_CURLY = 47;
  public static final int SUMA = 25;
  public static final int EXIT = 37;
  public static final int IF = 4;
  public static final int NUM_ALEATORIO = 35;
  public static final int PROCESS = 15;
  public static final int LETPAR_NUM = 31;
  public static final int BOOLEAN = 40;
  public static final int DECIMAL = 39;
  public static final int EOF = 0;
  public static final int GETELEMENT = 55;
  public static final int EQUAL = 43;
  public static final int TRUE = 12;
  public static final int error = 1;
  public static final int COMA = 46;
  public static final int HUNTIL = 8;
  public static final int ONLOAD = 59;
  public static final int NUMBER = 53;
  public static final int STRINGVAR = 42;
  public static final int GLOBAL = 60;
  public static final int CLOSE_BRACKET = 50;
  public static final int OPEN_BRACKET = 49;
  public static final int THENWHILE = 11;
  public static final int REDIRECT = 61;
  public static final int OPEN_PARENTHESIS = 51;
  public static final int ASC = 29;
  public static final int COLON = 44;
  public static final int CLOSE_CURLY = 48;
  public static final int ELSE = 6;
  public static final int WHILE = 10;
  public static final int INVALIDATE = 58;
  public static final int INSERT = 9;
  public static final int DIFFERENTIATION = 20;
  public static final int THEN = 5;
  public static final int END = 3;
  public static final int IDVARIABLE = 57;
  public static final int STRING = 14;
  public static final int CLOSE_PARENTHESIS = 52;
  public static final int FALSE = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INIT",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "REPEAT",
  "HUNTIL",
  "INSERT",
  "WHILE",
  "THENWHILE",
  "TRUE",
  "FALSE",
  "STRING",
  "PROCESS",
  "OR",
  "AND",
  "NOT",
  "EQUALIZATION",
  "DIFFERENTIATION",
  "LESSTHAN",
  "GREATERTHAN",
  "LESS",
  "GREATER",
  "SUMA",
  "RESTA",
  "DIV",
  "MULT",
  "ASC",
  "DESC",
  "LETPAR_NUM",
  "LETIMPAR_NUM",
  "REVERSE",
  "CARACTER_ALEATORIO",
  "NUM_ALEATORIO",
  "ALERT_INFO",
  "EXIT",
  "INTEGER",
  "DECIMAL",
  "BOOLEAN",
  "CHAR",
  "STRINGVAR",
  "EQUAL",
  "COLON",
  "SEMICOLON",
  "COMA",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS",
  "NUMBER",
  "SYMCHAR",
  "GETELEMENT",
  "IDPARAMETER",
  "IDVARIABLE",
  "INVALIDATE",
  "ONLOAD",
  "GLOBAL",
  "REDIRECT"
  };
}

