
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.chtml.save;

/** CUP generated class containing symbol constants. */
public class SaveSym {
  /* terminals */
  public static final int HREF = 13;
  public static final int FALLO = 11;
  public static final int EQUAL = 2;
  public static final int DATE = 12;
  public static final int OPEN_C = 3;
  public static final int OPEN_B = 5;
  public static final int NAME = 18;
  public static final int CODE = 14;
  public static final int COLON = 7;
  public static final int ID = 8;
  public static final int ACIERTO = 10;
  public static final int STRING = 16;
  public static final int CLOSE_C = 4;
  public static final int EOF = 0;
  public static final int NUMBER = 15;
  public static final int CLOSE_B = 6;
  public static final int error = 1;
  public static final int DB = 17;
  public static final int INTENTO = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EQUAL",
  "OPEN_C",
  "CLOSE_C",
  "OPEN_B",
  "CLOSE_B",
  "COLON",
  "ID",
  "INTENTO",
  "ACIERTO",
  "FALLO",
  "DATE",
  "HREF",
  "CODE",
  "NUMBER",
  "STRING",
  "DB",
  "NAME"
  };
}

