// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: html.flex

package com.chtml.parser;
//imports
import static com.chtml.parser.sym.*;
import java_cup.runtime.Symbol;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class ChtmlLex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\1\6\4\0\1\7\1\10\1\11\3\0\1\12"+
    "\1\0\1\13\1\0\1\14\12\0\1\15\1\16\1\17"+
    "\2\0\1\20\1\21\1\22\1\23\1\24\1\0\1\25"+
    "\1\26\1\27\1\0\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\0\1\36\1\37\1\40\1\41\1\42\1\0"+
    "\1\43\1\44\1\0\1\45\1\3\1\46\1\0\1\47"+
    "\1\0\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\0\1\61\1\62\1\63\1\64\1\65"+
    "\1\66\1\0\1\67\1\70\1\71\1\72\1\42\1\73"+
    "\1\74\1\75\1\76\12\0\1\3\32\0\1\3\u01df\0"+
    "\1\3\177\0\13\3\35\0\2\3\5\0\1\3\57\0"+
    "\1\3\240\0\1\3\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\2\0\1\3\1\4\1\5"+
    "\1\6\1\7\1\10\1\1\1\11\1\12\15\1\1\13"+
    "\1\14\2\0\11\1\1\15\11\1\1\16\1\0\7\1"+
    "\1\17\2\1\1\20\13\1\1\21\1\22\3\1\1\0"+
    "\1\1\1\23\3\1\1\24\16\1\1\25\3\1\1\26"+
    "\1\27\3\1\1\30\1\31\1\32\1\1\1\16\2\1"+
    "\1\33\2\1\1\34\12\1\1\35\1\36\5\1\1\37"+
    "\1\1\1\40\1\41\1\1\1\42\1\43\1\1\1\44"+
    "\3\1\1\45\4\1\1\46\2\1\1\47\1\50\3\1"+
    "\1\51\4\1\1\52\4\1\1\53\1\1\1\54\1\55"+
    "\1\1\1\56\2\1\1\57\7\1\1\60\2\1\1\61"+
    "\1\62\1\1\1\63\1\64\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\77\0\176\0\275\0\374\0\u013b\0\u017a\0\176"+
    "\0\176\0\176\0\u01b9\0\176\0\176\0\u01f8\0\176\0\176"+
    "\0\u0237\0\u0276\0\u02b5\0\u02f4\0\u0333\0\u0372\0\u03b1\0\u03f0"+
    "\0\u042f\0\u046e\0\u04ad\0\u04ec\0\u052b\0\176\0\176\0\u01b9"+
    "\0\u056a\0\u05a9\0\u05e8\0\u0627\0\u0666\0\u06a5\0\u06e4\0\u0723"+
    "\0\u0762\0\u07a1\0\77\0\u07e0\0\u081f\0\u085e\0\u089d\0\u08dc"+
    "\0\u091b\0\u095a\0\u0999\0\u09d8\0\u052b\0\u0a17\0\u0a56\0\u0a95"+
    "\0\u0ad4\0\u0b13\0\u0b52\0\u0b91\0\u0bd0\0\77\0\u0c0f\0\u0c4e"+
    "\0\77\0\u0c8d\0\u0ccc\0\u0d0b\0\u0d4a\0\u0d89\0\u0dc8\0\u0e07"+
    "\0\u0e46\0\u0e85\0\u0ec4\0\u0f03\0\u0f42\0\77\0\u0f81\0\u0fc0"+
    "\0\u0fff\0\u103e\0\u107d\0\77\0\u10bc\0\u10fb\0\u113a\0\77"+
    "\0\u1179\0\u11b8\0\u11f7\0\u1236\0\u1275\0\u12b4\0\u12f3\0\u1332"+
    "\0\u1371\0\u13b0\0\u13ef\0\u142e\0\u146d\0\u14ac\0\77\0\u14eb"+
    "\0\u152a\0\u1569\0\77\0\77\0\u15a8\0\u15e7\0\u1626\0\77"+
    "\0\u1665\0\77\0\u16a4\0\u056a\0\u16e3\0\u1722\0\77\0\u1761"+
    "\0\u17a0\0\77\0\u17df\0\u181e\0\u185d\0\u189c\0\u18db\0\u191a"+
    "\0\u1959\0\u1998\0\u19d7\0\u1a16\0\77\0\77\0\u1a55\0\u1a94"+
    "\0\u1ad3\0\u1b12\0\u1b51\0\77\0\u1b90\0\77\0\77\0\u1bcf"+
    "\0\77\0\77\0\u1c0e\0\77\0\u1c4d\0\u1c8c\0\u1ccb\0\77"+
    "\0\u1d0a\0\u1d49\0\u1d88\0\u1dc7\0\77\0\u1e06\0\u1e45\0\77"+
    "\0\77\0\u1e84\0\u1ec3\0\u1f02\0\77\0\u1f41\0\u1f80\0\u1fbf"+
    "\0\u1ffe\0\77\0\u203d\0\u207c\0\u20bb\0\u20fa\0\77\0\u2139"+
    "\0\77\0\77\0\u2178\0\77\0\u21b7\0\u21f6\0\77\0\u2235"+
    "\0\u2274\0\u22b3\0\u22f2\0\u2331\0\u2370\0\u23af\0\77\0\u23ee"+
    "\0\u242d\0\77\0\77\0\u246c\0\77\0\77\0\77";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\2\1\12\1\2\1\13\1\14\1\15\2\2"+
    "\1\16\22\2\1\17\1\20\1\2\1\21\1\22\1\23"+
    "\2\2\1\24\1\2\1\25\1\26\3\2\1\27\1\30"+
    "\1\2\1\31\1\32\1\33\1\2\1\34\4\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\25\2\2\0"+
    "\30\2\101\0\1\3\74\0\1\2\4\0\1\35\4\0"+
    "\1\2\1\0\1\2\3\0\25\2\2\0\30\2\6\6"+
    "\1\36\70\6\7\7\1\37\67\7\12\40\1\41\64\40"+
    "\1\2\4\0\1\2\4\0\1\2\1\0\1\2\3\0"+
    "\25\2\2\0\1\42\30\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\25\2\2\0\13\2\1\43\15\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\25\2"+
    "\2\0\1\2\1\44\27\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\25\2\2\0\1\42\7\2\1\45"+
    "\2\2\1\46\2\2\1\47\12\2\4\0\1\2\4\0"+
    "\1\2\1\0\1\2\3\0\25\2\2\0\16\2\1\50"+
    "\12\2\4\0\1\2\4\0\1\2\1\0\1\2\3\0"+
    "\25\2\2\0\5\2\1\51\12\2\1\52\10\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\25\2\2\0"+
    "\4\2\1\53\24\2\4\0\1\2\4\0\1\2\1\0"+
    "\1\2\3\0\25\2\2\0\1\2\1\54\21\2\1\55"+
    "\5\2\4\0\1\2\4\0\1\2\1\0\1\2\3\0"+
    "\25\2\2\0\15\2\1\56\13\2\4\0\1\2\4\0"+
    "\1\2\1\0\1\2\3\0\25\2\2\0\1\2\1\57"+
    "\14\2\1\60\12\2\4\0\1\2\4\0\1\2\1\0"+
    "\1\2\3\0\25\2\2\0\20\2\1\61\10\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\25\2\2\0"+
    "\5\2\1\62\20\2\1\63\2\2\4\0\1\2\4\0"+
    "\1\2\1\0\1\2\3\0\25\2\2\0\11\2\1\64"+
    "\16\2\2\65\1\0\74\65\12\41\1\66\64\41\1\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\1\2"+
    "\1\67\1\2\1\70\1\2\1\71\1\72\1\73\1\2"+
    "\1\74\2\2\1\75\1\76\1\2\1\77\1\100\4\2"+
    "\2\0\2\2\1\67\1\2\1\70\2\2\1\71\1\72"+
    "\1\73\1\2\1\74\2\2\1\75\1\76\1\2\1\77"+
    "\1\100\6\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\22\2\1\101\6\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\3\2"+
    "\1\102\25\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\5\2\1\103\23\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\1\2"+
    "\1\104\27\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\13\2\1\105\15\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\15\2"+
    "\1\106\13\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\11\2\1\107\17\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\5\2"+
    "\1\110\23\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\14\2\1\111\14\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\14\2"+
    "\1\112\14\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\3\2\1\113\25\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\4\2"+
    "\1\114\24\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\24\2\1\115\4\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\3\2"+
    "\1\116\25\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\25\2\1\117\3\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\17\2"+
    "\1\120\11\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\4\2\1\121\23\2\12\41\1\122"+
    "\64\41\1\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\14\2\1\123\1\2\1\124\2\2\1\125\3\2"+
    "\2\0\16\2\1\123\1\2\1\124\2\2\1\125\5\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\7\2"+
    "\1\126\15\2\2\0\11\2\1\126\17\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\2\2\1\127\22\2"+
    "\2\0\3\2\1\127\25\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\130\3\0\4\2\1\131\20\2\2\0\5\2"+
    "\1\131\23\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\12\2\1\132\1\133\11\2\2\0\14\2\1\132"+
    "\1\133\13\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\7\2\1\134\15\2\2\0\11\2\1\134\17\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\15\2"+
    "\1\135\7\2\2\0\17\2\1\135\11\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\2\2\1\136\1\2"+
    "\1\137\10\2\1\140\7\2\2\0\3\2\1\136\1\2"+
    "\1\137\11\2\1\140\11\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\4\2\1\141\2\2\1\142\15\2"+
    "\2\0\5\2\1\141\3\2\1\142\17\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\12\2"+
    "\1\143\16\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\3\2\1\144\25\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\21\2"+
    "\1\145\7\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\16\2\1\146\2\2\1\147\1\2"+
    "\1\150\5\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\22\2\1\151\6\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\7\2"+
    "\1\152\21\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\6\2\1\153\22\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\5\2"+
    "\1\154\23\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\2\2\1\155\26\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\13\2"+
    "\1\156\15\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\11\2\1\157\17\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\21\2"+
    "\1\160\7\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\22\2\1\161\6\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\5\2"+
    "\1\162\23\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\22\2\1\163\5\2\12\41\1\122"+
    "\4\41\1\164\57\41\1\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\3\2\1\165\21\2\2\0\4\2"+
    "\1\165\24\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\20\2\1\166\4\2\2\0\22\2\1\166\6\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\22\2"+
    "\1\167\2\2\2\0\31\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\7\2\1\170\15\2\2\0\11\2"+
    "\1\170\17\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\1\171\24\2\2\0\1\2\1\171\27\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\5\2\1\172"+
    "\17\2\2\0\7\2\1\172\21\2\4\0\1\2\4\0"+
    "\1\2\1\0\1\2\3\0\15\2\1\173\7\2\2\0"+
    "\17\2\1\173\11\2\4\0\1\2\4\0\1\2\1\0"+
    "\1\2\3\0\13\2\1\174\11\2\2\0\15\2\1\174"+
    "\13\2\4\0\1\2\4\0\1\2\1\0\1\2\3\0"+
    "\20\2\1\175\4\2\2\0\22\2\1\175\6\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\16\2\1\176"+
    "\6\2\2\0\20\2\1\176\10\2\4\0\1\2\4\0"+
    "\1\2\1\0\1\2\3\0\11\2\1\177\13\2\2\0"+
    "\13\2\1\177\15\2\4\0\1\2\4\0\1\2\1\0"+
    "\1\2\3\0\1\200\24\2\2\0\1\2\1\200\27\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\23\2"+
    "\1\201\1\2\2\0\25\2\1\201\3\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\20\2\1\202\4\2"+
    "\2\0\22\2\1\202\6\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\25\2\2\0\7\2\1\203\21\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\25\2"+
    "\2\0\12\2\1\204\16\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\25\2\2\0\21\2\1\205\7\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\25\2"+
    "\2\0\20\2\1\206\10\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\25\2\2\0\14\2\1\207\14\2"+
    "\4\0\1\2\4\0\1\210\1\0\1\2\3\0\25\2"+
    "\2\0\31\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\10\2\1\211\20\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\5\2"+
    "\1\212\23\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\11\2\1\213\17\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\16\2"+
    "\1\214\12\2\4\0\1\2\4\0\1\215\1\0\1\2"+
    "\3\0\25\2\2\0\31\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\25\2\2\0\10\2\1\216\20\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\24\2"+
    "\1\217\2\0\26\2\1\217\2\2\4\0\1\2\4\0"+
    "\1\2\1\0\1\2\3\0\20\2\1\220\4\2\2\0"+
    "\22\2\1\220\6\2\4\0\1\2\4\0\1\2\1\0"+
    "\1\2\3\0\2\2\1\221\22\2\2\0\3\2\1\221"+
    "\25\2\4\0\1\2\4\0\1\2\1\0\1\2\3\0"+
    "\3\2\1\222\21\2\2\0\4\2\1\222\24\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\21\2\1\223"+
    "\3\2\2\0\23\2\1\223\5\2\4\0\1\2\4\0"+
    "\1\2\1\0\1\2\3\0\10\2\1\224\14\2\2\0"+
    "\12\2\1\224\16\2\4\0\1\2\4\0\1\2\1\0"+
    "\1\2\3\0\7\2\1\225\15\2\2\0\11\2\1\225"+
    "\17\2\4\0\1\2\4\0\1\2\1\0\1\2\3\0"+
    "\7\2\1\226\15\2\2\0\11\2\1\226\17\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\4\2\1\227"+
    "\20\2\2\0\5\2\1\227\23\2\4\0\1\2\4\0"+
    "\1\2\1\0\1\2\3\0\12\2\1\230\12\2\2\0"+
    "\14\2\1\230\14\2\4\0\1\2\4\0\1\2\1\0"+
    "\1\2\3\0\20\2\1\231\4\2\2\0\22\2\1\231"+
    "\6\2\4\0\1\2\4\0\1\2\1\0\1\2\3\0"+
    "\11\2\1\232\13\2\2\0\13\2\1\232\15\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\25\2\2\0"+
    "\20\2\1\233\10\2\4\0\1\2\4\0\1\2\1\0"+
    "\1\2\3\0\25\2\2\0\2\2\1\234\26\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\25\2\2\0"+
    "\15\2\1\235\13\2\4\0\1\2\4\0\1\2\1\0"+
    "\1\2\3\0\25\2\2\0\6\2\1\236\12\2\1\237"+
    "\7\2\4\0\1\2\4\0\1\2\1\0\1\2\3\0"+
    "\25\2\2\0\22\2\1\240\6\2\4\0\1\2\4\0"+
    "\1\2\1\0\1\2\3\0\25\2\2\0\20\2\1\241"+
    "\10\2\4\0\1\2\4\0\1\2\1\0\1\2\3\0"+
    "\25\2\2\0\3\2\1\242\25\2\4\0\1\2\4\0"+
    "\1\2\1\0\1\2\3\0\25\2\2\0\1\2\1\243"+
    "\27\2\4\0\1\2\4\0\1\2\1\0\1\2\3\0"+
    "\14\2\1\244\10\2\2\0\16\2\1\244\12\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\20\2\1\245"+
    "\4\2\2\0\22\2\1\245\6\2\4\0\1\2\4\0"+
    "\1\2\1\0\1\2\3\0\14\2\1\246\10\2\2\0"+
    "\16\2\1\246\12\2\4\0\1\2\4\0\1\2\1\0"+
    "\1\2\3\0\15\2\1\247\7\2\2\0\17\2\1\247"+
    "\11\2\4\0\1\2\4\0\1\2\1\0\1\2\3\0"+
    "\2\2\1\250\22\2\2\0\3\2\1\250\25\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\1\251\24\2"+
    "\2\0\1\2\1\251\27\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\4\2\1\252\20\2\2\0\5\2"+
    "\1\252\23\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\16\2\1\253\12\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\16\2"+
    "\1\254\12\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\1\2\1\255\27\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\11\2"+
    "\1\256\17\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\25\2\2\0\12\2\1\257\16\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\25\2\2\0\13\2"+
    "\1\260\15\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\13\2\1\261\11\2\2\0\15\2\1\261\13\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\13\2"+
    "\1\262\11\2\2\0\15\2\1\262\13\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\20\2\1\263\4\2"+
    "\2\0\22\2\1\263\6\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\20\2\1\264\4\2\2\0\22\2"+
    "\1\264\6\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\16\2\1\265\6\2\2\0\20\2\1\265\10\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\25\2"+
    "\2\0\23\2\1\266\5\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\25\2\2\0\25\2\1\267\3\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\25\2"+
    "\2\0\14\2\1\270\14\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\25\2\2\0\27\2\1\271\1\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\25\2"+
    "\2\0\11\2\1\272\17\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\7\2\1\273\15\2\2\0\11\2"+
    "\1\273\17\2\4\0\1\2\4\0\1\2\1\0\1\2"+
    "\3\0\4\2\1\274\20\2\2\0\5\2\1\274\23\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\25\2"+
    "\2\0\15\2\1\275\13\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\25\2\2\0\11\2\1\276\17\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\25\2"+
    "\2\0\5\2\1\277\23\2\4\0\1\2\4\0\1\2"+
    "\1\0\1\2\3\0\25\2\2\0\7\2\1\300\21\2"+
    "\4\0\1\2\4\0\1\2\1\0\1\2\3\0\13\2"+
    "\1\301\11\2\2\0\15\2\1\301\13\2\4\0\1\2"+
    "\4\0\1\2\1\0\1\2\3\0\1\302\24\2\2\0"+
    "\1\2\1\302\27\2\4\0\1\2\4\0\1\2\1\0"+
    "\1\2\3\0\25\2\2\0\4\2\1\303\24\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\25\2\2\0"+
    "\13\2\1\304\15\2\4\0\1\2\4\0\1\2\1\0"+
    "\1\2\3\0\25\2\2\0\15\2\1\305\13\2\4\0"+
    "\1\2\4\0\1\2\1\0\1\2\3\0\5\2\1\306"+
    "\17\2\2\0\7\2\1\306\21\2\4\0\1\2\4\0"+
    "\1\2\1\0\1\2\3\0\25\2\2\0\26\2\1\307"+
    "\1\2";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9387];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\1\11\2\1\2\0\3\11\1\1\2\11"+
    "\1\1\2\11\15\1\2\11\2\0\24\1\1\0\33\1"+
    "\1\0\165\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ChtmlLex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("OPTION: "+yytext());
                        return new Symbol(OPTION, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 54: break;
          case 2:
            { return new Symbol(SPACE, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 55: break;
          case 3:
            { System.out.println("(");
        return new Symbol(OPEN_PARENTHESIS, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 56: break;
          case 4:
            { System.out.println(")");
        return new Symbol(CLOSE_PARENTHESIS, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 57: break;
          case 5:
            { System.out.println("/");
        return new Symbol(DIV, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 58: break;
          case 6:
            { System.out.println("<");
        return new Symbol(LESS, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 59: break;
          case 7:
            { System.out.println("=");
        return new Symbol(EQUAL, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 60: break;
          case 8:
            { System.out.println(">");
        return new Symbol(GREATER, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 61: break;
          case 9:
            { System.out.println("[");
        return new Symbol(OPEN_BRACKET, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 62: break;
          case 10:
            { System.out.println("]");
        return new Symbol(CLOSE_BRACKET, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 63: break;
          case 11:
            { System.out.println(yytext());
        return new Symbol(STRING, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 64: break;
          case 12:
            { System.out.println(yytext());
        return new Symbol(CHAR, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 65: break;
          case 13:
            { System.out.println("id");
        return new Symbol(IDE, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 66: break;
          case 14:
            { /*empty*/
            }
            // fall through
          case 67: break;
          case 15:
            { System.out.println("C_P");
        return new Symbol(C_P, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 68: break;
          case 16:
            { System.out.println("alt");
        return new Symbol(ALT, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 69: break;
          case 17:
            { System.out.println("row");
        return new Symbol(ROW, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 70: break;
          case 18:
            { System.out.println("src");
        return new Symbol(SRC, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 71: break;
          case 19:
            { System.out.println("C_BR");
        return new Symbol(C_BR, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 72: break;
          case 20:
            { System.out.println("C_H1");
        return new Symbol(C_H1, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 73: break;
          case 21:
            { System.out.println("cols");
        return new Symbol(COLS, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 74: break;
          case 22:
            { System.out.println("href");
        return new Symbol(HREF, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 75: break;
          case 23:
            { System.out.println("name");
        return new Symbol(NAME, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 76: break;
          case 24:
            { System.out.println("rows");
        return new Symbol(ROWS, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 77: break;
          case 25:
            { System.out.println("text");
        return new Symbol(TEXT, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 78: break;
          case 26:
            { System.out.println("type");
        return new Symbol(TYPE, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 79: break;
          case 27:
            { System.out.println("C_DIV");
        return new Symbol(C_DIV, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 80: break;
          case 28:
            { System.out.println("C_IMG");
        return new Symbol(C_IMG, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 81: break;
          case 29:
            { System.out.println("class");
        return new Symbol(CLASS, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 82: break;
          case 30:
            { System.out.println("color");
        return new Symbol(COLOR, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 83: break;
          case 31:
            { System.out.println("radio");
        return new Symbol(RADIO, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 84: break;
          case 32:
            { System.out.println("width");
        return new Symbol(WIDTH, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 85: break;
          case 33:
            { System.out.println("C_BODY");
            return new Symbol(C_BODY, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 86: break;
          case 34:
            { System.out.println("C_GCIC");
            return new Symbol(C_GCIC, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 87: break;
          case 35:
            { System.out.println("C_HEAD");
            return new Symbol(C_HEAD, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 88: break;
          case 36:
            { System.out.println("C_LINK");
            return new Symbol(C_LINK, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 89: break;
          case 37:
            { System.out.println("C_SPAM");
        return new Symbol(C_SPAM, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 90: break;
          case 38:
            { System.out.println("column");
        return new Symbol(COLUMNS, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 91: break;
          case 39:
            { System.out.println("height");
        return new Symbol(HEIGHT, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 92: break;
          case 40:
            { System.out.println("number");
        return new Symbol(NUMBER, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 93: break;
          case 41:
            { System.out.println("C_INPUT");
        return new Symbol(C_INPUT, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 94: break;
          case 42:
            { System.out.println("C_TITLE");
            return new Symbol(C_TITLE, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 95: break;
          case 43:
            { System.out.println("onclick");
        return new Symbol(ONCLICK, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 96: break;
          case 44:
            { System.out.println("C_BUTTON");
        return new Symbol(C_BUTTON, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 97: break;
          case 45:
            { System.out.println("C_OPTION");
        return new Symbol(C_OPTION, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 98: break;
          case 46:
            { System.out.println("C_SELECT");
        return new Symbol(C_SELECT, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 99: break;
          case 47:
            { System.out.println("checkbox");
        return new Symbol(CHECKBOX, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 100: break;
          case 48:
            { System.out.println("font-size");
        return new Symbol(FONTSIZE, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 101: break;
          case 49:
            { System.out.println("C_TEXTAREA");
        return new Symbol(C_TEXTAREA, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 102: break;
          case 50:
            { System.out.println("background");
        return new Symbol(BACKGROUND, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 103: break;
          case 51:
            { System.out.println("text-align");
        return new Symbol(TEXTALIGN, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 104: break;
          case 52:
            { System.out.println("C_SCRIPTING");
        return new Symbol(C_SCRIPTING, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 105: break;
          case 53:
            { System.out.println("font-family");
        return new Symbol(FONTFAMILY, yyline + 1, yycolumn + 1, yytext());
            }
            // fall through
          case 106: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
