
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.chtml.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SPACE = 48;
  public static final int C_LINK = 12;
  public static final int C_DIV = 19;
  public static final int CHAR = 53;
  public static final int C_BR = 21;
  public static final int WIDTH = 44;
  public static final int CHECKBOX = 35;
  public static final int GREATER = 3;
  public static final int ONCLICK = 47;
  public static final int C_HEAD = 10;
  public static final int ROWS = 39;
  public static final int LESS = 2;
  public static final int FONTFAMILY = 29;
  public static final int OPTION = 49;
  public static final int C_INPUT = 15;
  public static final int C_IMG = 20;
  public static final int TYPE = 31;
  public static final int C_SPAM = 14;
  public static final int CLASS = 40;
  public static final int C_BODY = 13;
  public static final int C_P = 24;
  public static final int DIV = 4;
  public static final int C_SCRIPTING = 8;
  public static final int C_GCIC = 9;
  public static final int C_BUTTON = 22;
  public static final int BACKGROUND = 26;
  public static final int FONTSIZE = 28;
  public static final int C_H1 = 23;
  public static final int EOF = 0;
  public static final int EQUAL = 7;
  public static final int C_TEXTAREA = 16;
  public static final int error = 1;
  public static final int NUMBER = 33;
  public static final int CLOSE_BRACKET = 52;
  public static final int OPEN_BRACKET = 51;
  public static final int HEIGHT = 45;
  public static final int IDE = 36;
  public static final int NAME = 37;
  public static final int COLOR = 27;
  public static final int OPEN_PARENTHESIS = 5;
  public static final int COLS = 38;
  public static final int TEXTALIGN = 30;
  public static final int RADIO = 34;
  public static final int COLUMNS = 42;
  public static final int C_OPTION = 18;
  public static final int ALT = 46;
  public static final int ROW = 41;
  public static final int HREF = 25;
  public static final int STRING = 50;
  public static final int CLOSE_PARENTHESIS = 6;
  public static final int C_SELECT = 17;
  public static final int TEXT = 32;
  public static final int C_TITLE = 11;
  public static final int SRC = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LESS",
  "GREATER",
  "DIV",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS",
  "EQUAL",
  "C_SCRIPTING",
  "C_GCIC",
  "C_HEAD",
  "C_TITLE",
  "C_LINK",
  "C_BODY",
  "C_SPAM",
  "C_INPUT",
  "C_TEXTAREA",
  "C_SELECT",
  "C_OPTION",
  "C_DIV",
  "C_IMG",
  "C_BR",
  "C_BUTTON",
  "C_H1",
  "C_P",
  "HREF",
  "BACKGROUND",
  "COLOR",
  "FONTSIZE",
  "FONTFAMILY",
  "TEXTALIGN",
  "TYPE",
  "TEXT",
  "NUMBER",
  "RADIO",
  "CHECKBOX",
  "IDE",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "ROW",
  "COLUMNS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "SPACE",
  "OPTION",
  "STRING",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "CHAR"
  };
}

